SquareHouseShifting/SquareHouseShifting/Controllers/HomeController.cs
using SquareHouseShifting.Models;
using SquareHouseShifting.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SquareHouseShifting.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult CalculateDistance()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult Quote(string start, string end, string distance)
        {
            QuoteRepository repositpory = new QuoteRepository();

            var model = repositpory.GenerateQuote(start, end, distance, User.Identity.Name);



            return RedirectToAction("QuoteDetail", new { id = model.Id });
        }

        public ActionResult QuoteDetail(Guid id)
        {
            QuoteRepository repositpory = new QuoteRepository();

            QuoteDetailsViewModel model = new QuoteDetailsViewModel();

            var quoteInfo = repositpory.GetQuoteById(id);
            var currentUserName = User.Identity.Name;
            ApplicationUser user = new ApplicationUser();
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                user = db.Users.FirstOrDefault(u => u.UserName == currentUserName);
            }

            model.Name = user.FirstName + " " + user.LastName;
            model.Email = user.Email;
            model.Id = quoteInfo.Id;
            model.IsPurchased = quoteInfo.IsPurchased;
            model.QuoteInfoList = quoteInfo.QuoteInfoList;
            model.QuotePrice = quoteInfo.QuotePrice;
            model.StartAddress = quoteInfo.StartAddress;
            model.UserId = quoteInfo.UserId;
            model.Distance = quoteInfo.Distance;
            model.EndAddress = quoteInfo.EndAddress;

            return View(model);
        }


    }
}

SquareHouseShifting/SquareHouseShifting/Controllers/PurchaseController.cs
using SquareHouseShifting.Models;
using SquareHouseShifting.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SquareHouseShifting.Controllers
{
    public class PurchaseController : Controller
    {
        // GET: Purchase
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DoPurchase(Guid Id, string UserId, decimal QuotePrice)
        {
            PurchaseViewModel model = new PurchaseViewModel();
            model.QuoteId = Id;
            model.UserId = UserId;
            model.TotalPrice = QuotePrice;
            return View(model);
        }
        [Authorize]
        [HttpPost]
        public ActionResult CreatePurchase(PurchaseViewModel purchase)
        {
            PurchaseRepository repo = new PurchaseRepository();

            var result = repo.CreatePurchase(purchase);
            return result ? RedirectToAction("PurchaseSuccess") : RedirectToAction("PurchaseFailure");
        }

        public ActionResult PurchaseSuccess()
        {
            return View();
        }

        public ActionResult PurchaseFilure()
        {
            return View();
        }

    }
}

SquareHouseShifting/SquareHouseShifting/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SquareHouseShifting/SquareHouseShifting/Views/Home/CalculateDistance.cshtml
@{
    ViewBag.Title = "Calculate Distance";
}
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRnkB0vy0wtecwLglj1eCIBFMrENrrG48&callback=initialize"
        type="text/javascript"></script>
<style type="text/css">
    #map_canvas {
        height: 100%;
    }
</style>

<div class="panel-body">
    @using (Html.BeginForm("Quote", "Home", FormMethod.Get, new { @class = "form-horizontal", role = "form" }))
    {
        <div class="form-group">
            <label class="col-md-2 control-label" for="start">From Address: </label>
            <div class="col-md-10">
                <input class="form-control" type="text" name="start" id="start" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label" for="end">To Address: </label>
            <div class="col-md-10">
                <input class="form-control" type="text" name="end" id="end" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" class="btn btn-info" value="Calculate Distance" onclick="calcRoute()" />
            </div>
        </div>
        <div class="form-group">

            <label class="col-md-2 control-label" for="distance">Distance (Miles): </label>
            <div class="col-md-10">
                <input class="form-control" type="text" name="distance" id="distance" readonly="true" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary" value="Get Quote" />
            </div>
        </div>
    }
</div>
<div class="row">
    <div id="map_canvas" style="height:500px;"></div>
</div>
<script type="text/javascript">
    var directionDisplay;
    var directionsService;
    var map;

    function initialize() {
        directionsService = new google.maps.DirectionsService();
        directionsDisplay = new google.maps.DirectionsRenderer();
        var melbourne = new google.maps.LatLng(-37.813187, 144.96298);
        var myOptions = {
            zoom: 12,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            center: melbourne
        }

        map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
        directionsDisplay.setMap(map);

        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (position) {
                initialLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                map.setCenter(initialLocation);
            });
        }
    }

    function calcRoute() {
        var start = document.getElementById("start").value;
        var end = document.getElementById("end").value;
        var distanceInput = document.getElementById("distance");

        var request = {
            origin: start,
            destination: end,
            travelMode: google.maps.DirectionsTravelMode.WALKING
        };

        directionsService.route(request, function (response, status) {
            if (status == google.maps.DirectionsStatus.OK) {
                directionsDisplay.setDirections(response);
                distanceInput.value = Math.round((response.routes[0].legs[0].distance.value / 1000) * 0.621371 * 100, -2) / 100;
            }
        });
    }
</script>
<script type="text/javascript">
    initialize();
</script>

SquareHouseShifting/SquareHouseShifting/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Us";
}
<h2>@ViewBag.Title.</h2>


<address>
    Square House Shifting<br />
    Redmond, NY 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@sqhshifting.com">Support@sqhshifting.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@sqhshifting.com">Marketing@sqhshifting.com</a>
</address>

SquareHouseShifting/SquareHouseShifting/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Square House Shifting</h1>
    <p><a href="/Home/CalculateDistance" class="btn btn-primary btn-lg">Calculate Distance</a></p>
</div>

<div class="row">
    <div class="col-md-8">
        <h2>Getting started</h2>
        <p>
            Shifting one’s household has never been an easy task. There are many packers and movers which are not registered and have no real office spaces.
            The whole process of moving begins with making numerous calls to various packers and movers,
            asking them to visit the house and struggling to decide the mover that suits one’s requirements.
        </p>
    </div>
</div>
<br />
<div class="row">
    <div style="">
        <div id="thumbnail-slider">
            <div class="inner">
                <ul>
                    <li>
                        <a class="thumb" href="img/1.jpg"></a>
                    </li>
                    <li>
                        <a class="thumb" href="img/2.jpg"></a>
                    </li>
                    <li>
                        <a class="thumb" href="img/3.jpg"></a>
                    </li>
                    <li>
                        <a class="thumb" href="img/4.jpg"></a>
                    </li>
                    <li>
                        <a class="thumb" href="img/5.jpg"></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

SquareHouseShifting/SquareHouseShifting/Views/Home/QuoteDetail.cshtml
@model SquareHouseShifting.Models.QuoteDetailsViewModel
@{
    ViewBag.Title = "Quote";
}

<h2>Quote</h2>

<div class="row">

    @using (Html.BeginForm("DoPurchase", "Purchase", FormMethod.Get, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.Hidden("UserId",Model.UserId)
        @Html.Hidden("Id",Model.Id)
        @Html.Hidden("QuotePrice",Model.QuotePrice)
        <div class="form-group">
            <label style="font-weight: normal" class="col-md-2 control-label" for="start">Name:</label>
            <div class="col-md-10">
                <label class="col-md-7 control-label" for="start">@Model.Name</label>
            </div>
        </div>
        <div class="form-group">
            <label style="font-weight: normal" class="col-md-2 control-label" for="start">Email:</label>
            <div class="col-md-10">
                <label class="col-md-7 control-label" for="start">@Model.Email</label>
            </div>
        </div>
        <div class="form-group">
            <label style="font-weight: normal" class="col-md-2 control-label" for="start">Address:</label>
            <div class="col-md-10">
                <label class="col-md-7 control-label" for="start">@Model.StartAddress</label>
            </div>
        </div>
        <hr />
        <div class="form-group">
            <label style="font-weight: normal" class="col-md-2 control-label" for="start">Start:</label>
            <div class="col-md-10">
                <label class="col-md-7 control-label" for="start">@Model.StartAddress</label>
            </div>
        </div>
        <div class="form-group">
            <label style="font-weight: normal" class="col-md-2 control-label" for="start">End:</label>
            <div class="col-md-10">
                <label class="col-md-7 control-label" for="start">@Model.EndAddress</label>
            </div>
        </div>
        <div class="form-group">
            <label style="font-weight: normal" class="col-md-2 control-label" for="start">Distance:</label>
            <div class="col-md-10">
                <label class="col-md-7 control-label" for="start">@Model.Distance (Miles)</label>
            </div>
        </div>
        foreach (var info in Model.QuoteInfoList)
        {
            <div class="form-group">
                <label style="font-weight: normal" class="col-md-2 control-label" for="start">@info.Key :</label>
                <div class="col-md-10">
                    <label class="col-md-7 control-label" for="start">$ @info.value</label>
                </div>
            </div>
        }
        <hr />
        <div class="form-group">
            <b><label class="col-md-2 control-label" for="start">QuotePrice:</label></b>
            <div class="col-md-10">
                <b><label class="col-md-7 control-label" for="start">$ @Model.QuotePrice</label></b>
            </div>
        </div>
        <hr />
        <div class="form-group">
            <div class="col-md-offset-7 col-md-7">
                <input type="submit" class="btn btn-primary" value="Purchase" />
            </div>
        </div>

    }
</div>